export async function chatWithValya(prompt: string, imageBase64?: string, model: string = "gemini-2.5-flash", apiKeyOverride?: string): Promise<string> {
    try {
        const apiKey = apiKeyOverride || process.env.GEMINI_API_KEY;
        if (!apiKey) {
            throw new Error("Gemini API key is not defined.");
        }

        const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

        let contents: any[] = [];
        
        if (imageBase64) {
            contents.push({
                role: "user",
                parts: [
                    { text: prompt },
                    { inlineData: { mimeType: "image/jpeg", data: imageBase64 } }
                ]
            });
        } else {
            contents.push({
                role: "user",
                parts: [{ text: prompt }]
            });
        }

        const payload = {
            contents: contents,
            generationConfig: {
                temperature: 0.4
            }
        };

        const response = await fetch(endpoint, {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(payload),
            cache: "no-store"
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Gemini API Error: ${response.status} ${err}`);
        }

        const data = await response.json();
        
        if (data.candidates && data.candidates.length > 0) {
            let text = data.candidates[0].content.parts[0].text;
            // Strip out markdown code block tags if the model returns them
            if (text.startsWith('```json')) {
                text = text.replace(/^```json\s*/, '').replace(/\s*```$/, '');
            } else if (text.startsWith('```')) {
                text = text.replace(/^```\s*/, '').replace(/\s*```$/, '');
            }
            return text;
        } else {
            throw new Error("No response generated by Gemini.");
        }

    } catch (error: any) {
        console.error("Failed to connect to Gemini API:", error);
        let errorMsg = error.message;
        if (error.cause) {
            errorMsg += " | Cause: " + (error.cause.message || String(error.cause));
        }
        throw new Error(errorMsg);
    }
}
