export async function chatWithValya(prompt: string, imageBase64?: string, unusedModel?: string, apiKeyOverride?: string): Promise<string> {
    try {
        const apiKey = apiKeyOverride || process.env.HUGGINGFACE_TOKEN || process.env.HUGGINGFACE_API_KEY;
        if (!apiKey) {
            throw new Error("Hugging Face API key is not defined.");
        }

        const endpoint = "https://router.huggingface.co/v1/chat/completions";
        
        let messages: any[] = [];
        let modelToUse = "Qwen/Qwen2.5-7B-Instruct"; // Default text model
        
        if (imageBase64) {
            modelToUse = "Qwen/Qwen3-VL-8B-Instruct"; // Use vision model if image exists
            // Fix base64 prefix if not present
            const finalBase64 = imageBase64.startsWith("data:image") ? imageBase64 : `data:image/jpeg;base64,${imageBase64}`;
            messages.push({
                role: "user",
                content: [
                    { type: "text", text: prompt },
                    { type: "image_url", image_url: { url: finalBase64 } }
                ]
            });
        } else {
            messages.push({
                role: "user",
                content: prompt
            });
        }

        const payload = {
            model: modelToUse,
            messages: messages,
            max_tokens: 2000,
            temperature: 0.4
        };

        const response = await fetch(endpoint, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${apiKey}`
            },
            body: JSON.stringify(payload),
            cache: "no-store"
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Hugging Face API Error: ${response.status} ${err}`);
        }

        const data = await response.json();
        
        if (data.choices && data.choices.length > 0) {
            let text = data.choices[0].message.content;
            // Strip out markdown code block tags if the model returns them
            if (text.startsWith('```json')) {
                text = text.replace(/^```json\s*/, '').replace(/\s*```$/, '');
            } else if (text.startsWith('```')) {
                text = text.replace(/^```\s*/, '').replace(/\s*```$/, '');
            }
            return text;
        } else {
            throw new Error("No response generated by Hugging Face.");
        }

    } catch (error: any) {
        console.error("Failed to connect to Hugging Face API:", error);
        let errorMsg = error.message;
        if (error.cause) {
            errorMsg += " | Cause: " + (error.cause.message || String(error.cause));
        }
        throw new Error(errorMsg);
    }
}
