"use server";
import { chatWithValya } from '@/lib/valya-client';

export interface CropSuggestion {
    name: string;
    budget: string;
    duration: string;
    profit: string;
    description: string;
}

export async function getCropSuggestions(
    message: string,
    apiKey: string
) {
    try {

        const systemInstruction = "You are an expert crop advisor. Your goal is to help farmers maximize their profit by suggesting the best crops to grow for the current season and the upcoming season. Return a JSON object with a 'suggestions' key containing an array of crop objects. Each object MUST have: 'name' (string), 'budget' (string), 'duration' (string), 'profit' (string), and 'description' (string). Return ONLY the JSON object, no markdown or extra text.";
        const fullPrompt = systemInstruction + "\n\nUser request: " + message;
        
        const payload = {
            model: "Qwen/Qwen2.5-7B-Instruct",
            messages: [{ role: "user", content: fullPrompt }],
            max_tokens: 2000,
            temperature: 0.7
        };

        const hfToken = apiKey || process.env.HUGGINGFACE_TOKEN || process.env.HUGGINGFACE_API_KEY;
        if (!hfToken) {
            throw new Error("Hugging Face API key is not defined.");
        }

        const response = await fetch("https://router.huggingface.co/v1/chat/completions", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Authorization": `Bearer ${hfToken}`
            },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const err = await response.text();
            throw new Error(`Hugging Face API Error: ${response.status} ${err}`);
        }

        const data = await response.json();
        let text = data.choices?.[0]?.message?.content;

        if (!text) {
            throw new Error("No response generated by Hugging Face.");
        }

        try {
            // Strip markdown JSON tags if present
            if (text.startsWith('```json')) {
                text = text.replace(/^```json\s*/, '').replace(/\s*```$/, '');
            } else if (text.startsWith('```')) {
                text = text.replace(/^```\s*/, '').replace(/\s*```$/, '');
            }

            const jsonMatch = text.match(/\{[\s\S]*\}/);
            const jsonToParse = jsonMatch ? jsonMatch[0] : text;
            const parsed = JSON.parse(jsonToParse);
            if (!parsed.suggestions || !Array.isArray(parsed.suggestions)) {
                throw new Error("Invalid structure: missing 'suggestions' array.");
            }
            return { suggestions: parsed.suggestions as CropSuggestion[] };
        } catch (parseError) {
            console.error("JSON Parse Error with Gemini:", text);
            throw parseError;
        }

    } catch (error: any) {
        console.error("Hugging Face Crop Suggestion Error:", error);

        const isAuthError =
            error.status === 401 ||
            error.status === 403 ||
            error.message?.toLowerCase().includes("unauthorized") ||
            error.message?.toLowerCase().includes("invalid api key");

        if (isAuthError) {
            return { error: "Authentication failed. Please verify your Hugging Face API Key." };
        }

        return { error: error.message || "An unexpected error occurred during crop suggestions." };
    }
}
